GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Super Popular Title2",
    "author": "Super Popular Author2",
    "url": "https://www.google.com/",
    "likes": 1000002
}
###
DELETE  http://localhost:3001/api/blogs/64bf4485ed816c7f58ec89c5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZ2dlci50ZXN0IiwiaWQiOiI2NGNlZjczYjQ0ZGMzOWVkMzI1YzA4MmIiLCJpYXQiOjE2OTEyODUzMjgsImV4cCI6MTY5MTI4ODkyOH0.BAsOztx09HujfPG2l0QUr3HMfFcw8B079IJr6iYPEnk
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "jagger.test",
    "password": "password",
    "name": "jagger"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "jagger.test",
    "password": "password"
}