GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Super Popular Title2",
    "author": "Super Popular Author2",
    "url": "https://www.google.com/",
    "likes": 1000002
}
###
DELETE  http://localhost:3001/api/blogs/64be8c46f082d58c0e6099a4
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "jagger.unit.test",
    "password": "password",
    "name": "jagger"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "jagger.unit",
    "password": "password"
}