GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Super Popular Title2",
    "author": "Super Popular Author2",
    "url": "https://www.google.com/",
    "likes": 1000001
}
###
DELETE  http://localhost:3001/api/blogs/:id
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "jagger.dev",
    "password": "",
    "name": "jagger"
}